import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  javaSidebar: [{type: 'autogenerated', dirName: 'java'}],
  middlewareSidebar: [{type: 'autogenerated', dirName: 'middleware'}],
  projectSidebar: [{type: 'autogenerated', dirName: 'project'}],
  interviewSidebar: [{type: 'autogenerated', dirName: 'interview'}],
};

export default sidebars;
